### ISSUE TITLE
Add ignored paths by configuration

### ISSUE THREAD

**Issue by dhermyt** [synergy-software/CodeTopology#1]
Some paths or file extensions should not be analyzed.

**Comment by cezarypiatek** [comment]
I've added  **DirToExclude** parameter which accepts a list of directories to exclude (parameter is case sensitive). By default CodeTopology ignores the following directories: "Bin","Obj","Lib","bin","obj","packages","lib","App_Data","node_modules", "bower_components".
If you want to extend this list use DirToExclude parameter as follows:

To ignore single _dist_ directory

``` powershell
.\GenerateReport.ps1 -VCS Git -DirToExclude dist  -CheckoutDir path_to_your_repository_checkout_dir
```

To ignore _dist1_ and _dist2_ directories

``` powershell
.\GenerateReport.ps1 -VCS Git -DirToExclude dist1, dist2  -CheckoutDir path_to_your_repository_checkout_dir
```
